### ISSUE TITLE
ENH: Tambah Barang Baru

### ISSUE THREAD

**Issue by rhynarukami** [lutfiihsan/stok.digitaljb.com#2]
- [x] Barcode diganti ke serial number
 - [x] Ketika buat barcode (serial number) baru, tidak langsung muncul.
 - [x] kesulitan edit barcode (serial number) yang sudah terdata,
 - [x] hapus barcode (serial number) tidak bekerja
 - [x] ketika submit tambah barang, data barcode (serial number) menghilang tanpa terdata kedalam barang yg terkait.
 - [x] stok pada tab barcode dihilangkan

**Comment by lutfiihsan** [comment]
Klo sudah terceklist, commitannya dihubungkan ke issue ini

**Comment by rhynarukami** [comment]
[feat: tambah file style.css](https://github.com/System-Cerdas-inc/stok.digitaljb.com/commit/30bd53e269c7b4ee1f19be09ad0b949b8e8676d9)

[fix: hapus <br>](https://github.com/System-Cerdas-inc/stok.digitaljb.com/commit/6050368681fdad92cfc76add3033f5fc40319dad)

[enh: barcode jadi serial number, aksi ubah serial number, stok ditiadakan](https://github.com/System-Cerdas-inc/stok.digitaljb.com/commit/3ad043bb35ad3a18e16ec447fed2595956048757)

**Comment by lutfiihsan** [comment]
Ada caranya, bukan copas kek gitu

**Comment by lutfiihsan** [comment]
Pas mau merge, arahkan ke development lalu pilih issue yg terkait
